# Конфиг локального форка прод-снапшота.
# Никаких p2p-peer-address — нода НЕ должна синхронироваться с проводом.

plugin = eosio::chain_plugin
plugin = eosio::net_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::http_plugin
plugin = eosio::state_history_plugin
plugin = eosio::producer_plugin
plugin = eosio::producer_api_plugin

http-server-address = 0.0.0.0:8888
p2p-listen-endpoint = 0.0.0.0:9876
access-control-allow-origin = *
http-validate-host = false
abi-serializer-max-time-ms = 200000

chain-state-history = true
trace-history = true
state-history-endpoint = 0.0.0.0:8080

wasm-runtime = eos-vm
net-threads = 2
max-transaction-time = 2000

chain-state-db-size-mb = 2048
blocks-log-stride = 10000
max-retained-block-files = 10

state-history-log-retain-blocks = 1000

# Локальное производство блоков под dev-ключом (заменён в snapshot-fork.bin)
producer-name = eosio
signature-provider = EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
enable-stale-production = true
